### ISSUE TITLE
NLP with classification and vector  spaces: Perform sentiment analysis of tweets using logistic regression and then naïve Bayes  

### ISSUE THREAD

**Issue by TeAmP0is0N** [osDFS/YouthIcon#15] opened 2020-06-21 14:52 UTC

**Comment by vikram7599** [comment] 2020-06-23 06:51
Hi, I would like to work on this issue.

**Comment by kapilbindal** [comment] 2020-06-23 06:57
Okay, So this issue is assigned to @vikram7599  now

**Comment by vikram7599** [comment] 2020-06-23 07:04
Is there any specific dataset you guys want me to use?

**Comment by kapilbindal** [comment] 2020-06-23 07:23
You can work on whatever you find best.

**Comment by kapilbindal** [comment] 2020-06-23 11:56
@vikram7599 As you are not an SCI participant, then I can't assign this issue to you. You can coordinate with @TeAmP0is0N to work on this issue, till then I am retracting this issue from you.

**Comment by vikram7599** [comment] 2020-06-23 15:25
Hi Kapil, I have messaged you on the osDFS slack channel, and given you the reason. Please assign this issue to me.

**Comment by ajaynair710** [comment] 2020-06-27 06:35
I would like to work on this issue.

**Comment by simarpreetsingh-019** [comment] 2020-06-27 08:13
I would Like to work on this issue, working on sentiment analysis by using Logistic regression.

**Comment by kapilbindal** [comment] 2020-06-27 09:52
Hey @simarpreetsingh-019  as @ajaynair710 approached first, I'll be assigning this issue to him. You can check out other issues! We have many.

**Closed** 2020-08-18 07:01 UTC
Labels: SCI-2020
